# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - local: .python.gitlab-ci.yml
  - local: .pages.gitlab-ci.yml

stages:
  - lint
  - build
  - test
  - deploy

# Cache to speed up subsequent jobs
cache:
  paths:
    - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SAST_EXCLUDED_PATHS: venv/,log/
