---
.python-setup:
  image: python:slim
  before_script:
    - python --version ; pip --version
    - apt-get update && apt-get install -y --no-install-recommends git
    - pip install flit
    - flit install --only-deps --deps develop
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

python-test:
  extends: .python-setup
  stage: test
  script:
    - pytest
  artifacts:
    when: always
    expire_in: 7 day
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

python-lint:
  extends: .python-setup
  stage: lint
  script:
    - git init
    - pre-commit run --all-files

python-build:
  extends: .python-setup
  stage: build
  script:
    - flit build --no-use-vcs
  artifacts:
    paths:
      - dist/*

variables:
  FLIT_ROOT_INSTALL: 1
